"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var heroes_1 = require("./heroes");
var party_1 = require("./party");
var arthur = new heroes_1.Fighter('Arthur the fat', 'green');
var baszogep = new heroes_1.Bard('Baszógép');
var hokuszpok = new heroes_1.Warlock('Hókuszpók', 'Laothira');
var myParty = new party_1.Party();
myParty.addHero(arthur);
myParty.addHero(baszogep);
myParty.addHero(hokuszpok);
console.log(myParty.getStatus());
myParty.getPayment(4800);
console.log(myParty.getStatus());
myParty.retireHeroes();
console.log(myParty.getStatus());
myParty.getPayment(200);
console.log(myParty.getStatus());
myParty.retireHeroes();
console.log(myParty.getStatus());
